### ISSUE TITLE
Script Stops Before Time Parameters

### ISSUE THREAD

**Issue by meganmetzger** [casmlab/get-nytimes-articles#3]
Hi,

I'm hoping you can help with this. I am trying to use this script to run a search over a number of years. The output file seems to stop before the first day of the first month, with about 200 results. Any idea of what could be going wrong?

Thanks,

Megan

**Comment by libbyh** [comment]
Do you get any errors or just a stop? What time period are you trying? I can try to recreate the problem and do a little troubleshooting, but no, I'm not sure what's happening without knowing more.

**Comment by meganmetzger** [comment]
I don't get an error, I don't get any notification at all. It looks like
the code has worked perfectly, but it only produces jsons for 16 pages of
results. Right now, I am trying to get the entire year of 1990, but I tried
it once using 1990 1 1 and 1990 12 31 and then again with 1990 1 1 and 1991
1 1 to make sure I didn't make an error in the date and got exactly the
same results.

**Comment by libbyh** [comment]
I recreated the problem (sort of). You should see a 403 error in your log file if we found the same problem.

I got through 13 pages of results for 1990-01-01 and 16 pages of results for 1990-01-02, then got a 403 error that killed the script. I changed my settings to start at 1990-01-03, and it's working again. Something's happening on the 17th page of 1990-01-02, and I will look into it. In the meantime, you can probably try changing your settings to start on the day after the script failed, and once I get it fixed you can go back and get the data in the gap. My log file (below) shows different results for 429 (too many requests) and 403 (forbidden), and the 403 kills the script.

## Files for troubleshooting:
Here's my settings file:
```
[files]
logfile = /Users/libbyh/Documents/git/casmlab/get-nytimes-articles/times-testing.log
json_folder = /Users/libbyh/Documents/git/casmlab/get-nytimes-articles/jsons/
tsv_file = /Users/libbyh/Documents/git/casmlab/get-nytimes-articles/output.tsv

[nytimes]
query = 
start_year = 1990
start_month = 1
start_day = 3
end_year = 1990
end_month = 12
end_day = 31
api_key =
```

Here's my log file:

```
INFO:root:Getting started.
INFO:root:Working on 19900101.
INFO:root:Working on 19900102.
ERROR:root:HTTPError on page 17 on 19900102 (err no. 403: Forbidden) Here's the URL of the call: http://api.nytimes.com/svc/search/v2/articlesearch.json?begin_date=19900102&end_date=19900102&page=17&api-key=79f85a3b9e1141a28c1197a66126a567
INFO:root:Quitting. You've probably reached your API limit for the day.
ERROR:root:Unexpected error: <type 'exceptions.SystemExit'>
INFO:root:Finished.
INFO:root:Getting started.
INFO:root:Working on 19900103.
INFO:root:Working on 19900104.
INFO:root:Working on 19900105.
ERROR:root:HTTPError on page 0 on 19900105 (err no. 429: ) Here's the URL of the call: http://api.nytimes.com/svc/search/v2/articlesearch.json?begin_date=19900105&end_date=19900105&page=0&api-key=79f85a3b9e1141a28c1197a66126a567
ERROR:root:HTTPError on page 1 on 19900105 (err no. 429: ) Here's the URL of the call: http://api.nytimes.com/svc/search/v2/articlesearch.json?begin_date=19900105&end_date=19900105&page=1&api-key=79f85a3b9e1141a28c1197a66126a567
INFO:root:Working on 19900106.
ERROR:root:HTTPError on page 0 on 19900106 (err no. 429: ) Here's the URL of the call: http://api.nytimes.com/svc/search/v2/articlesearch.json?begin_date=19900106&end_date=19900106&page=0&api-key=79f85a3b9e1141a28c1197a66126a567
ERROR:root:HTTPError on page 1 on 19900106 (err no. 429: ) Here's the URL of the call: http://api.nytimes.com/svc/search/v2/articlesearch.json?begin_date=19900106&end_date=19900106&page=1&api-key=79f85a3b9e1141a28c1197a66126a567
ERROR:root:HTTPError on page 2 on 19900106 (err no. 429: ) Here's the URL of the call: http://api.nytimes.com/svc/search/v2/articlesearch.json?begin_date=19900106&end_date=19900106&page=2&api-key=79f85a3b9e1141a28c1197a66126a567
ERROR:root:HTTPError on page 16 on 19900106 (err no. 403: Forbidden) Here's the URL of the call: http://api.nytimes.com/svc/search/v2/articlesearch.json?begin_date=19900106&end_date=19900106&page=16&api-key=79f85a3b9e1141a28c1197a66126a567
INFO:root:Quitting. You've probably reached your API limit for the day.
ERROR:root:Unexpected error: <type 'exceptions.SystemExit'>
INFO:root:Finished.
```

**Comment by libbyh** [comment]
I went back to the code to fix this, and lines 75-77 of `getTimesArticles.py` indicate that the (403 Forbidden) error is an API limit issue. Until I can make the script smarter about stopping and resuming, you have to manage your API limits by hand. Will make new issues for enhancements about 429 and 403 errors.

**Comment by libbyh** [comment]
@meganmetzger here's what I was able to get today while trying to fix this. Given the 1000 call limit, it'll likely take a couple days to get a whole year of data. 

[output.txt](https://github.com/casmlab/get-nytimes-articles/files/768140/output.txt)

**Comment by meganmetzger** [comment]
Thanks very much. This is workable. As a secondary question, I don't
suppose there is a way to search just the headlines, as you can do with the
fq function on individual NYT API searches? I tried altering the config
file and what I thought were the relevant parts of the code, but it didn't
seem to work. Obviously, no problem if this isn't something you've
addressed, but thought it might have come up previously. Thanks again for
looking into the issue I had. I appreciate your help.

**Comment by libbyh** [comment]
I haven't worked with headlines, but you can change the API query on line 56. You can add fq or whatever you need in there. You should be able to just change that line to reflect the API call you want to make. Here's the list of parameters, and I think you can build a test URL here too: http://developer.nytimes.com/article_search_v2.json
